### ISSUE TITLE
OpenCL library version

### ISSUE THREAD

**Issue by valery1707** [1Ridav/PengueeBot#4]
You use version [0.1.9](https://search.maven.org/#artifactdetails%7Corg.jocl%7Cjocl%7C0.1.9%7Cjar) which was released at 05-Apr-2013, but version [2.0.0](https://search.maven.org/#artifactdetails%7Corg.jocl%7Cjocl%7C2.0.0%7Cjar) was released at 12-May-2016.
Maybe you can upgrade version?

**Comment by 1Ridav** [comment]
I gotta move to another library instead, this one got a bunch of bugs on *nix systems. JOCL was used as a testing feature.
