### ISSUE TITLE
Инструмент GRAB делает скриншот только основного экрана

### ISSUE THREAD

**Issue by RinatG** [1Ridav/PengueeBot#9]
При наличии двух экранов стандартный PrintScreen делает скриншот экранов обоих мониторов, в т.ч. с разным разрешением.
Инструмент GRAB делает скриншот только одного экрана.
Так же возникла мысль, что и Position, и Action.searchRect позиционируются только в координатах основного экрана.
Есть идеи реализовать работу на двух экранах? Или хотя бы в том экране, в котором находится окно PengueeBot.

**Comment by 1Ridav** [comment]
Исправлено в версии 1.10.42 
Теперь грабятся все экраны
